// <auto-generated />
using System;
using ClyvoDayApiWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ClyvoDayApiWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912000822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.CareEvent", b =>
                {
                    b.Property<int>("CareEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CareEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TypeEvent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CareEventId");

                    b.HasIndex("PetId");

                    b.ToTable("CARE_EVENTS", (string)null);
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.CommunityPost", b =>
                {
                    b.Property<int>("CommunityPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityPostId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("UserId1")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CommunityPostId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("COMMUNITY_POSTS", (string)null);
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.DailyPetLog", b =>
                {
                    b.Property<int>("DailyPetLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyPetLogId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DailyPetLogType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Privacy")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("DailyPetLogId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PetId");

                    b.ToTable("DAILY_PET_LOGS", (string)null);
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("TutorId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PetId");

                    b.HasIndex("TutorId");

                    b.ToTable("PETS", (string)null);
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.PetMonitoring", b =>
                {
                    b.Property<int>("PetMonitoringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetMonitoringId"));

                    b.Property<string>("EnergyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Food")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("HydrationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Mood")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RecentActivities")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("SleepQuality")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Sociability")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<bool?>("TookMedication")
                        .HasColumnType("NUMBER(1)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("PetMonitoringId");

                    b.HasIndex("PetId");

                    b.ToTable("PET_MONITORINGS", (string)null);
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int>("TypeUser")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Tutor", b =>
                {
                    b.HasBaseType("ClyvoDayApiWeb.Domain.Models.User");

                    b.Property<int>("Achievement")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ScoreEngagement")
                        .HasColumnType("NUMBER(10)");

                    b.ToTable("TUTORS", (string)null);
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Veterinarian", b =>
                {
                    b.HasBaseType("ClyvoDayApiWeb.Domain.Models.User");

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.HasIndex("Crmv", "State")
                        .IsUnique()
                        .HasFilter("\"Crmv\" IS NOT NULL AND \"State\" IS NOT NULL");

                    b.ToTable("VETERINARIANS", (string)null);
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.CareEvent", b =>
                {
                    b.HasOne("ClyvoDayApiWeb.Domain.Models.Pet", "Pet")
                        .WithMany("CareEvents")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.CommunityPost", b =>
                {
                    b.HasOne("ClyvoDayApiWeb.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClyvoDayApiWeb.Domain.Models.User", null)
                        .WithMany("CommunityPosts")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.DailyPetLog", b =>
                {
                    b.HasOne("ClyvoDayApiWeb.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClyvoDayApiWeb.Domain.Models.Pet", "Pet")
                        .WithMany("DailyPetLogs")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Pet", b =>
                {
                    b.HasOne("ClyvoDayApiWeb.Domain.Models.Tutor", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.PetMonitoring", b =>
                {
                    b.HasOne("ClyvoDayApiWeb.Domain.Models.Pet", "Pet")
                        .WithMany("PetMonitorings")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Tutor", b =>
                {
                    b.HasOne("ClyvoDayApiWeb.Domain.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ClyvoDayApiWeb.Domain.Models.Tutor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Veterinarian", b =>
                {
                    b.HasOne("ClyvoDayApiWeb.Domain.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ClyvoDayApiWeb.Domain.Models.Veterinarian", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Pet", b =>
                {
                    b.Navigation("CareEvents");

                    b.Navigation("DailyPetLogs");

                    b.Navigation("PetMonitorings");
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.User", b =>
                {
                    b.Navigation("CommunityPosts");
                });

            modelBuilder.Entity("ClyvoDayApiWeb.Domain.Models.Tutor", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
